repo:
  master_repo_path: "C:/Github/TrueCharts Master" # The local filesystem path to your cloned TrueCharts master repository. (https://github.com/truecharts/public)
  master_repo_branch: "master" # The branch to pull updates from in the master repository (usually `master`).
  personal_repo_path: "C:/Github/truecharts_archive" # The local filesystem path to your cloned personal repository (your personal fork of TrueCharts from https://github.com/v3DJG6GL/truecharts_archive)
  personal_repo_branch: "dev" # The branch to apply updates to in your personal repository.

logging:
  level: info  # Sets the logging verbosity. Options are `debug`, `info`, or `error`.
  log_to_file: true  # If `true`, logs will be written to a file specified in `log_file`.
  log_file: logs/update.log # The path to the log file where logs will be saved.

git: # Below options are my personal options since I constantly test modifying files and don't want the hassle of reverting changes
  reset_type: hard  # Determines how the script resets your local repository before pulling updates. Options: ['hard', 'soft', 'none']
  clean_untracked: true  # If `true`, untracked files will be removed from the working tree.
  commit_after_finish: true # Automatically commits changes after the script finishes updating.
  push_commit_after_finish: true # Automatically pushes the committed changes to your personal repository.

multiprocessing:
  use_multiprocessing: true  # Enables multiprocessing for faster chart comparisons and updates. May not work on all systems.
  max_workers: 0  # The number of worker processes to use. Set to `0` to use the number of CPU cores.

folders_to_compare: # A list of chart directories to compare and update between the master and personal repositories. Options include `stable`, `incubator`, `system`, and `premium`.
  - stable
  - incubator
  - system
  - premium

update_README: true # If `true`, the script will update the `README.md` file in your personal repository with a changelog of updated apps.

branches_to_run:  # New key for setting multiple branches
  - dev
  - main

custom_images: # Override values from Master repo. Use this section incase you want to update an app or use an alternative package.
  autobrr: # Folder/Chart name to match
    app_version: "1.53.0" # Manually specify the app version
    image: # This section and below will override matching items within ix_values.yaml. Be sure to match the layout of ix_values.yaml.
      repository: ghcr.io/autobrr/autobrr
      pullPolicy: IfNotPresent
      tag: v1.53.0@sha256:0c3f93c653cfc8a20e722bd26a5d597a496c9ba714300ba7974a5aeb19bd6e31
  audiobookshelf:
    app_version: "2.17.5"
    image:
      repository: docker.io/advplyr/audiobookshelf
      tag: 2.17.5@sha256:aa88c9f4652872a2a72043511a87d17ec743b60f53e8024e9868ebec5aae59bd
      pullPolicy: IfNotPresent
  changedetection-io:
    app_version: "0.48.01"
    image:
      repository: ghcr.io/dgtlmoon/changedetection.io
      pullPolicy: IfNotPresent
      tag: 0.48.01@sha256:3709fb9b4a2ebe5c4002887b9623c767d6d5e76e37520bf2509a8208147a8ae2
  immich:
    app_version: "1.122.2"
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.122.2@sha256:27ceb1867f5501818c86188c62924bbfd3024d8f74395cd66d6a302b01d1b2cd
      pullPolicy: IfNotPresent
    mlImage:
      repository: ghcr.io/immich-app/immich-machine-learning
      pullPolicy: IfNotPresent
      tag: v1.122.2@sha256:5c4e7a25a01e4dd52e9b919a277a2d870af0a08094e4089c85708e402512a8aa
    mlCudaImage:
      repository: ghcr.io/immich-app/immich-machine-learning
      pullPolicy: IfNotPresent
      tag: v1.122.2-cuda@sha256:72346d75268b494f2b8b6bf2508f79bae8fa6e856a2119c5fbe881b9fa198f54
    mlOpenvinoImage:
      repository: ghcr.io/immich-app/immich-machine-learning
      pullPolicy: IfNotPresent
      tag: v1.122.2-openvino@sha256:0ca2d1c2694f727b34526496db067b1f402e56c8dc7665504d3a9058921c29c5
  jellystat:
    app_version: "1.1.1"
    image:
      repository: cyfershepard/jellystat
      tag: 1.1.1@sha256:912ad92ffa96b08323a59773393461b04713764b5a40ce0af7e73af4177feace
      pullPolicy: IfNotPresent
  local-ai:
    app_version: "2.24.1"
    image:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1@sha256:6a83b8be47681e9bac6afed46687c0e866f29a6b3be20cac71c8d0ae96eb26c1
    ffmpegImage:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1-ffmpeg-core@sha256:ff7885927d2db4a1d012af8528e538e69e5b8cf65f31a0245df78f13241b2636
    cublasCuda12Image:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1-cublas-cuda12-core@sha256:17adeaa600e2907d7f41da48214855851e8aaf9ed49b2b34590368350e259058
    cublasCuda12FfmpegImage:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1-cublas-cuda12-ffmpeg-core@sha256:d03837480c64812241e698f02f1db92476d92b9ced66501fa862c8831f127d28
    cublasCuda11Image:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1-cublas-cuda11-core@sha256:48c993368130bc5f4f73e913f91d798bfe23c7b81a4213843056e49218a7ef9d
    cublasCuda11FfmpegImage:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1-cublas-cuda11-ffmpeg-core@sha256:97be63e65c96e72e9c5246384585f5a6346fae24c0b232dfabae878546759c7f
    allInOneCuda12Image:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1-aio-gpu-nvidia-cuda-12@sha256:1b15e90429d2edcb24e2769fdef4430ba1a0a472952d119a8b5652ecc2668d26
    allInOneCuda11Image:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1-aio-gpu-nvidia-cuda-11@sha256:523b6a79b04236135cc04227ab52ecff260402f49154de83e5744cba7a1159a5
    allInOneCpuImage:
      repository: docker.io/localai/localai
      pullPolicy: IfNotPresent
      tag: v2.24.1-aio-cpu@sha256:c1163ffb140b2efcdbce77e2451602e2b26f97fc1842957d2c9dcb8baa4df7c2
  meshcentral:
    app_version: "1.1.35"
    image:
      repository: ghcr.io/ylianst/meshcentral
      pullPolicy: IfNotPresent
      tag: 1.1.35@sha256:171c9b6e5ef8df7dfa2dcfc5d9a1a24b2eade0bce7f73ae1926c3a15855359d0
  nzbget:
    app_version: "24.5.0"
    image:
      repository: ghcr.io/elfhosted/nzbget
      pullPolicy: IfNotPresent
      tag: 24.5@sha256:8861eae1bdf7b5be8986dcfb75b793948652d3a63c5b0d355a88a99519027dca
  ollama:
    app_version: "0.5.1"
    image:
      repository: docker.io/ollama/ollama
      pullPolicy: IfNotPresent
      tag: 0.5.1@sha256:722ce8caba5f8b8bd2ee654b2e29466415be3071a704e3f4db1702b83c885f76
    rocmImage:
      repository: docker.io/ollama/ollama
      pullPolicy: IfNotPresent
      tag: 0.5.1-rocm@sha256:321d60288d0c5f1254241837cdce349793b16ac4a9ae3a6221a895243f263dad
    uiImage:
      repository: ghcr.io/open-webui/open-webui
      pullPolicy: IfNotPresent
      tag: latest@sha256:ee76db7339ab326fb3822ca22fd5de9b81b165c270d465fbca8fca3b80471db0
  prowlarr:
    app_version: "1.28.0.4862"
    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.28.0.4862@sha256:ff83bcd009f4556e5ee9a40e596dfaa3dd8313fe40246c1244416ffd8fc03ab5
      pullPolicy: IfNotPresent
  readarr:
    app_version: "0.4.5.2699"
    image:
      repository: ghcr.io/elfhosted/readarr-develop
      pullPolicy: IfNotPresent
      tag: 0.4.5.2699@sha256:947ec6ae98f5a0c51695c8401fc67729a76d5ae160e57f7049e65a258215edb6
  sabnzbd:
    app_version: ""
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      pullPolicy: IfNotPresent
      tag: 4.4.0@sha256:d2dbde184900504bf3636d2df74e466e223d6b2474b4d21a58c72eadfffa7e99
  sftpgo:
    app_version: "2.6.4"
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/drakkan/sftpgo
      tag: v2.6.4-plugins@sha256:9c21aeb99be0fe911c426267cb0bf357a2aec77e30ffef77f121713b1b9f87bb
  sonarr:
    app_version: "4.0.11.2680"
    image:
      repository: ghcr.io/onedr0p/sonarr
      tag: 4.0.11.2680@sha256:77827c4d76457a68e5c42fb141c312f9d1f0cbe96e984868cf859714cc53aa02
      pullPolicy: IfNotPresent
  syncthing:
    app_version: "1.28.1"
    image:
      repository: docker.io/syncthing/syncthing
      pullPolicy: IfNotPresent
      tag: 1.28.1@sha256:289b4ca86d77e4938d3e0af7d11f5c0a0fb786e469d5f697c25ab0f9e1f29f34
  tautulli:
    app_version: "2.15.0"
    image:
      repository: ghcr.io/tautulli/tautulli
      pullPolicy: IfNotPresent
      tag: v2.15.0@sha256:f13daee2a403a95a51902b2625de5f6b944f034e9cd790e9d2a0c5e84c9842cb