repo:
  master_repo_path: "F:/TrueNAS/TrueCharts_Master" # The local filesystem path to your cloned TrueCharts master repository. (https://github.com/truecharts/public)
  master_repo_branch: "master" # The branch to pull updates from in the master repository (usually `master`).
  personal_repo_path: "F:/TrueNAS/truecharts_archive" # The local filesystem path to your cloned personal repository (your personal fork of TrueCharts from https://github.com/v3DJG6GL/truecharts_archive)
  personal_repo_branch: "main" # The branch to apply updates to in your personal repository.

logging:
  level: info  # Sets the logging verbosity. Options are `debug`, `info`, or `error`.
  log_to_file: true  # If `true`, logs will be written to a file specified in `log_file`.
  log_file: logs/update.log # The path to the log file where logs will be saved.

git: # Below options are my personal options since I constantly test modifying files and don't want the hassle of reverting changes
  reset_type: hard  # Determines how the script resets your local repository before pulling updates. Options: ['hard', 'soft', 'none']
  clean_untracked: true  # If `true`, untracked files will be removed from the working tree.
  commit_after_finish: true # Automatically commits changes after the script finishes updating.
  push_commit_after_finish: false # Automatically pushes the committed changes to your personal repository.

multiprocessing:
  use_multiprocessing: true  # Enables multiprocessing for faster chart comparisons and updates.
  max_workers: 24     # Set as 75% of a Ryzen 9950X (32 threads)
  chunk_size: 40      # Larger chunks for better SSD utilization

io_optimization:
  buffer_size: 8388608  # 8MB buffer size
  use_direct_io: true   # Enable direct I/O for SSD
  concurrent_io: true   # Enable concurrent I/O operations

folders_to_compare: # A list of chart directories to compare and update between the master and personal repositories. Options include `stable`, `incubator`, `system`, and `premium`.
  - stable
  - system
  - premium

update_README: true # If `true`, the script will update the `README.md` file in your personal repository with a changelog of updated apps.

branches_to_run:  # New key for setting multiple branches
  - main

custom_images: # Override values from Master repo. Use this section incase you want to update an app or use an alternative package.
  traefik:
    app_version: "3.3.4"
    image:
      repository: ghcr.io/traefik/traefik
      pullPolicy: IfNotPresent
      tag: 3.3.4@sha256:cc11989f418e2cfe5e60fc40c92c1813be847f58eda15eced7d5ac890255ad9e
  blocky:
    app_version: "development"
    image:
      repository: ghcr.io/0xerr0r/blocky
      pullPolicy: IfNotPresent
      tag: development@sha256:a7ff25c5df11872e10beff1a0f226e5d751ee2799649d5713fdc0eaa7f843fe1
  plex:
    app_version: "1.41.5.9522"
    image:
      repository: ghcr.io/home-operations/plex
      pullPolicy: IfNotPresent
      tag: 1.41.5.9522@sha256:cb0310eb53e8ff6e51be2869b6de0425f649e631aa329e6ccf0c72ba580a8aa3
  overseerr:
    app_version: "1.33.2"
    image:
      repository: ghcr.io/sct/overseerr
      tag: develop@sha256:331708ee83cd192dd21abb4291fb5d3700aa49d0cd449e0b288995b6f69f5d22
      pullPolicy: IfNotPresent
  sabnzbd:
    app_version: "4.4.1"
    image:
      repository: ghcr.io/home-operations/sabnzbd
      pullPolicy: IfNotPresent
      tag: 4.4.1@sha256:95a8393d30e360297acee2dac8791e2787355d2880543200ce552f54ebab5c52
  prowlarr:
    app_version: "1.33.0"
    image:
      repository: ghcr.io/home-operations/prowlarr
      tag: 1.33.0@sha256:b1b4da4df605bec0ba810cf18abf91bc6569f5d8144a64da699cb78a7c2ec30c
      pullPolicy: IfNotPresent
  radarr:
    app_version: "5.21.1.9799"
    image:
      repository: ghcr.io/home-operations/radarr
      pullPolicy: IfNotPresent
      tag: 5.21.1.9799@sha256:13171f1d476b4b0c9a44191ae60ddd0d1581b9cd89f9c5f7a82be602c0f95096
  sonarr:
    app_version: "4.0.14.2938"
    image:
      repository: ghcr.io/home-operations/sonarr
      tag: 4.0.14.2938@sha256:acd5416ab9c36d017687820a32f09d09a4e25a5754aa5ebeae2e7c63d7609c13
      pullPolicy: IfNotPresent
  readarr:
    app_version: "0.4.7.2718"
    image:
      repository: ghcr.io/elfhosted/readarr-develop
      pullPolicy: IfNotPresent
      tag: 0.4.7.2718@sha256:68e5d14d1b57592fb05df7f434b611dfc845f96ba1daecb32cb85c65e6e4f26f
  tautulli:
    app_version: "nightly"
    image:
      repository: ghcr.io/tautulli/tautulli
      pullPolicy: IfNotPresent
      tag: nightly@sha256:5f4ce5792b23378e024110e8b3443b0e1a8fc88f91a5229abb5044daace4719f
  hammond:
    app_version: "0.0.25"
    image:
      repository: ghcr.io/heathouse/hammond
      tag: 0.0.25@sha256:23935bb5cfc2ae14ae815c0666f82d45ff61375ab58a720ab5ef7484a2bffe75
      pullPolicy: IfNotPresent
  dell-idrac-fan-controller:
    app_version: "latest"
    image:
      repository: ghcr.io/tigerblue77/dell_idrac_fan_controller
      pullPolicy: IfNotPresent
      tag: latest@sha256:eda09016a4acbee8883996f3b8cd4832a723200999bd037934675e75e2f00908
  minio:
    app_version: "2024-12-18"
    image:
      repository: docker.io/minio/minio
      pullPolicy: IfNotPresent
      tag: RELEASE.2024-12-18T13-15-44Z@sha256:1dce27c494a16bae114774f1cec295493f3613142713130c2d22dd5696be6ad3
  mylar:
    app_version: "nightly-be4fced5-ls458"
    image:
      repository: ghcr.io/linuxserver/mylar3
      tag: nightly-be4fced5-ls458@sha256:09f6b899a50e682070a3e597d4d17ebbc8b841001806a4f825b6ae68d0c454d8
      pullPolicy: IfNotPresent
  grocy:
    app_version: "nightly-be4fced5-ls458"
    image:
      repository: "ghcr.io/linuxserver/grocy"
      tag: "4.4.1@sha256:3064bd56fa72d8eba748fcee209c40b6e86639e274966247e584a979e9c61677"
      pullPolicy: "IfNotPresent"
  anything-llm:
    app_version: "latest"
    image:
      repository: ghcr.io/mintplex-labs/anything-llm
      pullPolicy: IfNotPresent
      tag: latest@sha256:8b5be67f760144b96bd23f780d2cf51919e2dddcd3707d6ae758e9e8d4b97f79